# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
trigger:
  - master
pr:
  - master

variables:
  GO_VERSION: 1.14
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: Checks
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make checks
        displayName: Run checks

  - job: UnitTest
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make unit-test
        displayName: Run unit test
      - script: bash <(curl https://codecov.io/bash) -t $CODECOV_UPLOAD_TOKEN
        env:
          CODECOV_UPLOAD_TOKEN: $(CODECOV_UPLOAD_TOKEN)
        displayName: Upload coverage to Codecov

  - job: BDDTest
    pool:
      vmImage: ubuntu-18.04
    strategy:
      parallel: 3
    timeoutInMinutes: 30
    steps:
      - script: sudo ufw enable
#      - script: sudo ufw allow from any to any port 8030 proto tcp
#      - script: sudo ufw status
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          function logout {
            docker logout
          }
          trap logout EXIT
          echo $DOCKER_PASSWORD | docker login docker.pkg.github.com --username $DOCKER_USER --password-stdin
          make bdd-test
        env:
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
        displayName: Run BDD tests
      - publish: test/bdd/docker-compose-$(System.JobPositionInPhase).log
        artifact: docker-compose-$(System.JobPositionInPhase).log
        condition: always()

  - job: Publish
    dependsOn:
      - Checks
      - UnitTest
      - BDDTest
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          function logout {
            docker logout
          }
          trap logout EXIT
          source ci/version_var.sh
          echo $DOCKER_PASSWORD | docker login docker.pkg.github.com --username $DOCKER_USER --password-stdin

          make issuer-adapter-rest-docker
          docker tag docker.pkg.github.com/trustbloc/edge-adapter/issuer-adapter-rest:latest ${ISSUER_ADAPTER_REST_PKG}:${ADAPTER_REST_TAG}
          docker push ${ISSUER_ADAPTER_REST_PKG}:${ADAPTER_REST_TAG}

          make rp-adapter-rest-docker
          docker tag docker.pkg.github.com/trustbloc/edge-adapter/rp-adapter-rest:latest ${RP_ADAPTER_REST_PKG}:${ADAPTER_REST_TAG}
          docker push ${RP_ADAPTER_REST_PKG}:${ADAPTER_REST_TAG}
        env:
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
